name: Build-Wrapper-TWR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Download & Install TypeWriter
        run: |
          curl -L --output ./TypeWriter.zip --url https://github.com/Dot-lua/TypeWriter/releases/latest/download/TypeWriter-Windows.zip
          tar -xf ./TypeWriter.zip
          ./TypeWriter.exe
          TypeWriter
          rm ./TypeWriter.zip
          rm ./TypeWriter.exe

      - name: Checkout
        uses: actions/checkout@v2.4.2
          
      - name: Build Bootstrap
        run: |
          TypeWriter buildexecutable --input=./Wrapper/Twr/src/ --output=./ --branch=Bootstrap
          ls
          
      - name: Build Wrapper
        run: |
          TypeWriter buildexecutable --input=./Wrapper/Twr/src/ --output=./ --branch=Main
          ls
          
      - name: Build Static
        run: |
          TypeWriter buildexecutable --input=./Wrapper/Twr/src/ --output=./ --branch=Static
          ls
          
      - name: Build WebHelper
        run: |
          TypeWriter buildexecutable --input=./Wrapper/Twr/src/ --output=./ --branch=WebHelper
          ls
          
      - name: Upload Libraries
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Wrapper-Twr-Libraries
          path: ./.TypeWriter/Build/
          
      - name: Upload Bootstrap
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Wrapper-Twr-Bootstrap
          path: ./.TypeWriter/Build/Bootstrap.twr
