name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  Mac-Build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        
      - name: Download & Install TypeWriter
        working-directory: ./BrowserView/
        run: |
          ls
          npm install
          npm run build
          ls
    
    
